[package]
edition = "2021"
name = "teocloud_teo"
version = "0.0.52-beta.4"

[lib]
crate-type = ["cdylib"]

[dependencies]
teo = { path = "../teo", version = "0.0.52-beta.3", features = ["data-source-mysql", "data-source-postgres", "data-source-sqlite", "data-source-mongodb"] }
to-mut = { version = "0.1.0" }
napi = { git = "https://github.com/victorteokw/napi-rs", rev = "ecf9958", default-features = false, features = ["napi5", "async", "chrono_date", "compat-mode"] }
napi-derive = "2.11.0"
chrono = { version = "0.4.24" }
bigdecimal = "0.3.0"
once_cell = "1.17.1"
tokio = "1.0"
inflector-plus = "0.11.7"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
